var menu = {
  "elem1":{
    "nom":"Accueil",
    "lien":"pokedex_accueil.html"
  },
  "elem2":{
    "nom":"Pokémons",
    "contenu":[
      {
        "nom":"Dracaufeu",
        "lien":"dracaufeu.html"
      },
      {
        "nom":"Voltali",
        "lien":""
      },
      {
        "nom":"Tyranocif",
        "lien":"tyranocif.html"
      },
      {
        "nom":"Gardevoir",
        "lien":""
      },
      {
        "nom":"Lucario",
        "lien":""
      },
      {
        "nom":"Amphinobi",
        "lien":""
      }
    ]
  }
};
